use_frameworks!

target 'ScreenBrightness_Example' do
  pod 'ScreenBrightness', :path => '../'

  target 'ScreenBrightness_Tests' do
    inherit! :search_paths

	pod 'ScreenBrightness', :path => '../'	    
  end
end
